export const ASYNC_SERVICE_DEFAULT_PROVIDER_NAME = 'base'
export const ASYNC_SERVICE_HANDLER_TYPE = 'ASYNC_SERVICE_HANDLER_TYPE'
export const ASYNC_SERVICE_PROVIDER_WEB_API_TYPE = 'ASYNC_SERVICE_PROVIDER_WEB_API_TYPE'
export const ASYNC_SERVICE_OPERATION_STATUS_CHANGE_EVENT = 'ASYNC_SERVICE_OPERATION_STATUS_CHANGE_EVENT'
export const STATE_SERVICE_RESET_ACTION_STATE = '__@lib_reset'

export const CACHE_NAMESPACES = {
  ASYNC_SERVICE_CONFIG: 'ASYNC_SERVICE_CONFIG',
  ASYNC_SERVICE_OPERATIONS_OPTIONS: 'ASYNC_SERVICE_OPERATIONS_OPTIONS',
  ASYNC_SERVICE_HANDLER_PROXY_1: 'ASYNC_SERVICE_HANDLER_PROXY_1',
  ASYNC_SERVICE_OPERATION_STATUS: 'ASYNC_SERVICE_OPERATION_STATUS',
  ASYNC_SERVICE_EVENTS_SUBSCIBERS: 'ASYNC_SERVICE_EVENTS_SUBSCIBERS',
  STATE_SERVICE_RAW_SLICES: 'STATE_SERVICE_RAW_SLICES',
  STATE_SERVICE_PREFERENCES: 'STATE_SERVICE_PREFERENCES',
  STATE_SERVICE_FORMATTED_ACTIONS: 'STATE_SERVICE_FORMATTED_ACTIONS',
  STATE_SERVICE_SLICE_SELECTORS: 'STATE_SERVICE_SLICE_SELECTORS',
}

export const ASYNC_SERVICE_STATUSES = { REQUEST: 'REQUEST', SUCCESS: 'SUCCESS', FAILURE: 'FAILURE' }
