const ASYNC_SERVICE_DEFAULT_PROVIDER_NAME = 'base'

const CACHE_NAMESPACES = {
  ASYNC_SERVICE_CONFIG: 'ASYNC_SERVICE_CONFIG',
  ASYNC_SERVICE_OPERATIONS_OPTIONS: 'ASYNC_SERVICE_OPERATIONS_OPTIONS',
}

export { ASYNC_SERVICE_DEFAULT_PROVIDER_NAME, CACHE_NAMESPACES }
